In [118]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sn
import pylab as pl

In [119]:
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny',
'Rainy','Sunny','Overcast','Overcast','Rainy']
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
Humidity= ['High','High','High','High','Normal','Normal','Normal','High','Normal','Normal','Normal','High','Normal','High']
Windy=['f','t','f','f','f','t','t','f','f','f','t','t','f','t']
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [120]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
weather_encoded = le.fit_transform(weather)
weather_encoded

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1], dtype=int64)

In [121]:
temp_encoded = le.fit_transform(temp)
temp_encoded

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2], dtype=int64)

In [122]:
humidity_encoded = le.fit_transform(Humidity)
humidity_encoded

array([0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0], dtype=int64)

In [123]:
wind_encoded = le.fit_transform(Windy)
wind_encoded

array([0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1], dtype=int64)

In [124]:
play_encoded = le.fit_transform(play)
play_encoded

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [125]:
features = list(zip(weather_encoded, temp_encoded, humidity_encoded, wind_encoded))
features

[(2, 1, 0, 0),
 (2, 1, 0, 1),
 (0, 1, 0, 0),
 (1, 2, 0, 0),
 (1, 0, 1, 0),
 (1, 0, 1, 1),
 (0, 0, 1, 1),
 (2, 2, 0, 0),
 (2, 0, 1, 0),
 (1, 2, 1, 0),
 (2, 2, 1, 1),
 (0, 2, 0, 1),
 (0, 1, 1, 0),
 (1, 2, 0, 1)]

In [126]:
from sklearn.linear_model import LogisticRegression
regr = LogisticRegression(solver = 'lbfgs', C = 0.01, max_iter = 300)
regr.fit(features, play_encoded)

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=300,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [127]:
play_encoded[0:5]

array([0, 0, 1, 1, 1], dtype=int64)

In [128]:
ypred = regr.predict(features)
ypred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [129]:
a_1 = regr.score(features, play_encoded)
a_1

0.6428571428571429

In [130]:
a_2 = regr.score(features, ypred)
a_2

1.0

In [131]:
from sklearn.metrics import accuracy_score
a_3 = accuracy_score(features, ypred)
a_3

ValueError: Classification metrics can't handle a mix of multiclass-multioutput and binary targets

In [132]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1, metric='manhattan')
knn.fit(features, play_encoded)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='manhattan',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [133]:
play_encoded

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [134]:
yhat = knn.predict(features)
yhat

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [135]:
b_1 = knn.score(features, play_encoded)
b_1

1.0

In [136]:
b_2 = knn.score(features, yhat)
b_2

1.0

In [137]:
from sklearn import svm
clf = svm.SVC(kernel = 'rbf', gamma = 'auto')
clf.fit(features, play_encoded)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [138]:
play_encoded

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [139]:
ypred_1 = clf.predict(features)
ypred_1

array([0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1], dtype=int64)

In [140]:
c_1 = clf.score(features, play_encoded)
c_1

0.8571428571428571

In [141]:
c_2 = clf.score(features, ypred_1)
c_2

1.0

In [142]:
from sklearn import tree
dt = tree.DecisionTreeClassifier()
dt.fit(features, play_encoded)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [143]:
play_encoded

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [144]:
yhat_1 = dt.predict(features)
yhat_1

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [145]:
d_1 = dt.score(features, play_encoded)
d_1

1.0

In [146]:
d_2 = dt.score(features, yhat_1)
d_2

1.0

In [147]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 1000)
rf.fit(features, play_encoded)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [148]:
play_encoded

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [149]:
ypred_2 = rf.predict(features)
ypred_2

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [150]:
e_2 = rf.score(features, ypred_2)
e_2

1.0

In [151]:
e_1 = rf.score(features, play_encoded)
e_1

1.0

In [152]:
from sklearn.naive_bayes import GaussianNB, MultinomialNB, BernoulliNB
gsn = GaussianNB()
gsn.fit(features, play_encoded)

GaussianNB(priors=None, var_smoothing=1e-09)

In [153]:
play_encoded

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [154]:
yhat_2 = gsn.predict(features)
yhat_2

array([0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [155]:
f_1 = gsn.score(features, play_encoded)
f_1

0.9285714285714286

In [156]:
f_2 = gsn.score(features, yhat_2)
f_2

1.0

In [157]:
mul = MultinomialNB()
mul.fit(features, play_encoded)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [158]:
play_encoded

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [159]:
ypred_3 = mul.predict(features)
ypred_3

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [160]:
g_1 = mul.score(features, play_encoded)
g_1

0.7857142857142857

In [161]:
g_2 = mul.score(features, ypred_3)
g_2

1.0

In [162]:
ber = BernoulliNB()
ber.fit(features, play_encoded)

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

In [163]:
yhat_3 = ber.predict(features)
yhat_3

array([0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0], dtype=int64)

In [164]:
h_1 = ber.score(features, play_encoded)
h_1

0.8571428571428571

In [165]:
h_2 = ber.score(features, yhat_3)
h_2

1.0

In [168]:
df = pd.DataFrame({'Training Score' : [a_1, b_1, c_1, d_1, e_1, f_1, g_1, h_1],
                  'Predicted Score' : [a_2, b_2, c_2, d_2, e_2, f_2, g_2, h_2],
                  }, index = ['Logistic Regression', 'KNN', 'SVM', 'Decision Tree', 'Random Forest', 'Gaussian NB', 'Multinomial NB', 'Bernoulli NB'])
df

Training Score  Predicted Score
Logistic Regression        0.642857              1.0
KNN                        1.000000              1.0
SVM                        0.857143              1.0
Decision Tree              1.000000              1.0
Random Forest              1.000000              1.0
Gaussian NB                0.928571              1.0
Multinomial NB             0.785714              1.0
Bernoulli NB               0.857143              1.0